import {
  faAngleDown,
  faAngleRight,
  faBars,
  faCaretDown,
  faSearch,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import React, { useContext, useEffect, useMemo, useRef, useState } from "react";

import ActiveLink from "../components/ActiveLink";
import BtnComp from "../components/BtnComp";
import styles from "../styles/Header/Header.module.css";
import { DataContext } from "../store/GlobalState";
import tranEn from "../utils/Translations/en.json";
import tranCh from "../utils/Translations/ch.json";
import tranKh from "../utils/Translations/kh.json";
import Link from "next/link";

const Header = ({ title, path }) => {
  let langs = [
    { img: "uk1.png", lang: "English", type: "en" },
    { img: "khmer.png", lang: "Khmer", type: "kh" },
    { img: "china.png", lang: "Chinese", type: "ch" },
  ];

  const router = useRouter();

  const { state, dispatch } = useContext(DataContext);
  const swLang = state.lang;
  const [currentLang, setCurrentLang] = useState(swLang.flag);
  const [isOpenMenu, setOpenMenu] = useState(false);
  const menuRef = useRef();
  const xREf = useRef();

  const [scrolled, setScrolled] = useState(false);

  const handleScroll = () => {
    const offset = window.scrollY;

    if (offset > 200) {
      setScrolled(true);
    } else {
      setScrolled(false);
    }
  };
  const menuHandler = () => {
    setOpenMenu((prev) => !prev);
  };
  useEffect(() => {
    isOpenMenu
      ? (document.body.style.overflow = "hidden")
      : (document.body.style.overflow = "auto");
  });
  useEffect(() => {
    let handleOpenMenu = (e) => {
      if (
        !xREf.current.contains(e.target) &&
        !menuRef.current.contains(e.target)
      ) {
        setOpenMenu(false);
      }
    };

    document.addEventListener("mousedown", handleOpenMenu, true);
    return () => {
      document.removeEventListener("mousedown", handleOpenMenu, true);
    };
  }, []);
  const [openProject, setOpenProject] = useState(false);
  const [menuDropDown, setMenuDropDown] = useState(false);
  const projectOnClickHandler = () => {
    setOpenProject(!openProject);
  };
  const href = "/projects";

  // set language

  const [langDrop, setLangDrop] = useState(false);
  const handleLangDropDown = () => {
    setLangDrop(!langDrop);
  };
  const handleChangeLangs = (item, type) => {
    dispatch({ type: "LANG", payload: { d_lang: type, flag: item } });
    localStorage.setItem("__lang_", type);
    setLangDrop(false);
  };
  let getLang = swLang.d_lang;
  let asPath = swLang.asPath;
  let translations = null;
  let changeLng = getLang.length > 0 ? getLang : asPath;
  if (changeLng == "kh") {
    translations = tranKh;
  } else if (changeLng == "en") {
    translations = tranEn;
  } else if (changeLng == "ch") {
    translations = tranCh;
  }
  const locAspath = router.asPath;

  console.log("change", locAspath.length);
  return (
    <div>
      <Head>
        <title>{title}</title>
        <link rel="icon" href="/logo.png" />
      </Head>
      {/* <meta name="description" content="Generated by create next app" /> */}
      <nav
        className={
          router.asPath === `${path}`
            ? styles.navbar_container
            : styles.navbar_container_relative
        }
        id="#navbar"
      >
        <div className={styles.navbar}>
          <div
            className={styles.navbar_logo}
            onClick={() => router.push(`/${changeLng}`)}
          >
            <Image
              alt="logo"
              src="/images/logo2.png"
              width={200}
              height={200}
              priority
            />
          </div>
          <div className={styles.navbar_link}>
            <ActiveLink href={locAspath.length <= 1 ? "/" : `/${changeLng}`}>
              {translations.Home}
            </ActiveLink>
            <ActiveLink href={`/${changeLng}/our-team`}>
              {translations["Our Team"]}
            </ActiveLink>
            <ActiveLink href={`/${changeLng}/our-services`}>
              {translations["Our Services"]}
            </ActiveLink>
            <ActiveLink href={`/${changeLng}/properties`}>
              {translations["Our Properties"]}
            </ActiveLink>
            <ActiveLink href={`/${changeLng}/about-us`}>
              {translations["About Us"]}
            </ActiveLink>
            <ActiveLink href={`/${changeLng}/careers`}>
              {translations.Careers}
            </ActiveLink>
            <ActiveLink href={`/${changeLng}/contact-us`}>
              {translations["Contact Us"]}
            </ActiveLink>
          </div>
          <div style={{ flexGrow: "1" }}></div>
          <div className={styles["lang"]}>
            <div
              className={styles["selected_lang"]}
              onClick={handleLangDropDown}
            >
              <Image
                width={100}
                height={100}
                alt="selected_lang"
                src={`/images/${
                  changeLng === "ch"
                    ? "china.png"
                    : changeLng === "kh"
                    ? "khmer.png"
                    : "uk1.png"
                }`}
                priority
              />
            </div>
            {langDrop && (
              <div className={styles["selection_lang"]}>
                {langs.map((item, i) => {
                  return (
                    <Link
                      className={styles["lang_details"]}
                      key={i}
                      onClick={() => handleChangeLangs(item.img, item.type)}
                      href={`/${item.type === "en" ? "" : item.type}`}
                    >
                      <div className={styles["select_lang"]}>
                        <Image
                          width={100}
                          height={100}
                          alt="selected_lang"
                          src={`/images/${item.img}`}
                          priority
                        />
                      </div>

                      <span>{item.lang}</span>
                    </Link>
                  );
                })}
              </div>
            )}
          </div>
          <div className={styles.get_intouch}>
            <FontAwesomeIcon
              icon={!isOpenMenu ? faBars : faXmark}
              width={20}
              height={20}
              className={`menuBar ${
                locAspath.length <= 1
                  ? "/"
                  : `/${changeLng}`
                  ? "inactive"
                  : "black"
              } ${isOpenMenu && "active"}`}
              onClick={menuHandler}
              ref={xREf}
            />
          </div>
        </div>
      </nav>
      <div className={`menu_drop_down ${isOpenMenu && "active"}`}>
        <div className={`menu_list ${isOpenMenu && "active"}`} ref={menuRef}>
          <div className="menu__list_frame">
            <ActiveLink
              href={locAspath.length <= 1 ? "/" : `/${changeLng}`}
              black
            >
              {translations.Home}
            </ActiveLink>
            <ActiveLink href={`/${changeLng}/our-team`} black>
              {translations["Our Team"]}
            </ActiveLink>
            <ActiveLink href={`/${changeLng}/our-services`} black>
              {translations["Our Services"]}
            </ActiveLink>
            <ActiveLink href={`/${changeLng}/properties`} black>
              {translations["Our Properties"]}
            </ActiveLink>
            <ActiveLink href={`/${changeLng}/about-us`} black>
              {translations["About Us"]}
            </ActiveLink>
            <ActiveLink href={`/${changeLng}/careers`} black>
              {translations.Careers}
            </ActiveLink>
            <ActiveLink href={`/${changeLng}/contact-us`} black>
              {translations["Contact Us"]}
            </ActiveLink>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Header;
